### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by spolu** [totemstech/dattss#36]
```
"TypeError: Cannot read property 'label' of undefined
    at http://dattss.com/js/dashboard/status_d.js:72:22
    at Array.forEach (native)
    at Object.$scope.update (http://dattss.com/js/dashboard/status_d.js:70:14)
    at http://dattss.com/js/dashboard/status_d.js:83:27
    at Array.forEach (native)
    at Object.$scope.update (http://dattss.com/js/dashboard/status_d.js:70:14)
    at Object.fn (http://dattss.com/js/dashboard/status_d.js:99:18)
    at Object.e.$digest (http://dattss.com/lib/angular/angular.min.js:86:409)
    at Object.e.$apply (http://dattss.com/lib/angular/angular.min.js:88:506)
    at SocketNamespace.<anonymous> (http://dattss.com/js/socket_s.js:22:22)", source: http://dattss.com/lib/angular/angular.min.js (62)
```

**Comment by n1t0** [comment]
Fixed
